version: '3.8'

services:
  images-service:
    build: .
    container_name: serpy-images-service
    ports:
      - "8001:8001"  # Exponer puerto al host
    volumes:
      # Montar directorio del host para las imágenes
      - /root/images:/images  # Las imágenes se guardarán en /root/images del VPS
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Para Linux
    networks:
      - serpy-network
    restart: unless-stopped

networks:
  serpy-network:
    external: true
