version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: serpy-redis
    ports:
      - "6379:6379"
    networks:
      - serpy-network
    restart: unless-stopped
    command: redis-server --bind 0.0.0.0

  images-service:
    build: .
    container_name: serpy-images-service
    ports:
      - "8001:8001"  # Exponer puerto al host
    volumes:
      # Montar directorio del host para las imágenes
      - /root/images:/images  # Las imágenes se guardarán en /root/images del VPS
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Para Linux
    networks:
      - serpy-network
    restart: unless-stopped
    depends_on:
      - redis

networks:
  serpy-network:
    external: true
