version: '3.8'

services:
  images-service:
    build: .
    container_name: images-service
    ports:
      - "8003:8000"
    volumes:
      - /var/www/images:/images
      - ./app:/app/app  # Para desarrollo con hot reload
    environment:
      - ENVIRONMENT=production
      - MONGODB_URI=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379/0
      - API_KEY=${API_KEY:-secure-api-key-here}
      - WEBHOOK_URL=${WEBHOOK_URL:-}
    depends_on:
      - redis
    networks:
      - serpy-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: images-redis
    volumes:
      - redis-data:/data
    networks:
      - serpy-network
    restart: unless-stopped

  celery-worker:
    build: .
    container_name: images-worker
    command: celery -A app.workers.celery_app worker --loglevel=info --concurrency=4
    volumes:
      - /var/www/images:/images
      - ./app:/app/app  # Para desarrollo
    environment:
      - ENVIRONMENT=production
      - MONGODB_URI=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379/0
      - API_KEY=${API_KEY:-secure-api-key-here}
    depends_on:
      - redis
    networks:
      - serpy-network
    restart: unless-stopped

  celery-beat:
    build: .
    container_name: images-beat
    command: celery -A app.workers.celery_app beat --loglevel=info
    volumes:
      - ./app:/app/app  # Para desarrollo
    environment:
      - ENVIRONMENT=production
      - MONGODB_URI=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - serpy-network
    restart: unless-stopped

  flower:
    build: .
    container_name: images-flower
    command: celery -A app.workers.celery_app flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - ENVIRONMENT=production
      - MONGODB_URI=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379/0
      - FLOWER_BASIC_AUTH=${FLOWER_USER:-admin}:${FLOWER_PASSWORD:-admin}
    depends_on:
      - redis
    networks:
      - serpy-network
    restart: unless-stopped

volumes:
  redis-data:

networks:
  serpy-network:
    external: true
